/**
 * Banco de perguntas da Arena Bíblica.
 *
 * REGRAS:
 * - `answer` é o índice da alternativa correta e NUNCA sai do servidor.
 * - `ref` aparece para o membro depois de responder (aprendizado > pontuação).
 * - Perguntas factuais e sem ambiguidade doutrinária, conferíveis no texto.
 * - Os ids são estáveis: mudar um id órfã as respostas já registradas.
 */
export interface ArenaQuestion {
  id: string;
  question: string;
  options: [string, string, string, string];
  answer: 0 | 1 | 2 | 3;
  ref: string;
}

export const QUESTIONS: ArenaQuestion[] = [
  {
    id: 'q001',
    question: 'Quantos dias e noites durou o dilúvio de chuva sobre a terra?',
    options: ['7', '30', '40', '100'],
    answer: 2,
    ref: 'Gênesis 7:12',
  },
  {
    id: 'q002',
    question: 'Quem foi lançado na cova dos leões?',
    options: ['Davi', 'Daniel', 'José', 'Jeremias'],
    answer: 1,
    ref: 'Daniel 6:16',
  },
  {
    id: 'q003',
    question: 'Qual é o primeiro livro da Bíblia?',
    options: ['Êxodo', 'Salmos', 'Gênesis', 'Mateus'],
    answer: 2,
    ref: 'Gênesis 1:1',
  },
  {
    id: 'q004',
    question: 'Quem construiu a arca?',
    options: ['Moisés', 'Abraão', 'Noé', 'Salomão'],
    answer: 2,
    ref: 'Gênesis 6:13-14',
  },
  {
    id: 'q005',
    question: 'Quantos livros tem o Novo Testamento?',
    options: ['27', '39', '66', '12'],
    answer: 0,
    ref: 'Cânon do NT',
  },
  {
    id: 'q006',
    question: 'Quem traiu Jesus por trinta moedas de prata?',
    options: ['Pedro', 'Tomé', 'Judas Iscariotes', 'João'],
    answer: 2,
    ref: 'Mateus 26:14-15',
  },
  {
    id: 'q007',
    question: 'Em que cidade Jesus nasceu?',
    options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'],
    answer: 2,
    ref: 'Mateus 2:1',
  },
  {
    id: 'q008',
    question: 'Quem derrotou o gigante Golias?',
    options: ['Saul', 'Davi', 'Sansão', 'Josué'],
    answer: 1,
    ref: '1 Samuel 17:50',
  },
  {
    id: 'q009',
    question: 'Qual apóstolo negou Jesus três vezes?',
    options: ['Pedro', 'André', 'Tiago', 'Filipe'],
    answer: 0,
    ref: 'Lucas 22:61',
  },
  {
    id: 'q010',
    question: 'Qual mar Moisés atravessou com o povo de Israel em seco?',
    options: ['Mar da Galileia', 'Mar Morto', 'Mar Vermelho', 'Mar Mediterrâneo'],
    answer: 2,
    ref: 'Êxodo 14:21-22',
  },
  {
    id: 'q011',
    question: 'Quantos discípulos Jesus escolheu como apóstolos?',
    options: ['7', '10', '12', '70'],
    answer: 2,
    ref: 'Lucas 6:13',
  },
  {
    id: 'q012',
    question: 'Quem foi engolido por um grande peixe?',
    options: ['Elias', 'Jonas', 'Amós', 'Oseias'],
    answer: 1,
    ref: 'Jonas 1:17',
  },
  {
    id: 'q013',
    question: 'Qual era o ofício de Jesus antes do ministério?',
    options: ['Pescador', 'Carpinteiro', 'Pastor de ovelhas', 'Coletor de impostos'],
    answer: 1,
    ref: 'Marcos 6:3',
  },
  {
    id: 'q014',
    question: 'Quem recebeu as tábuas dos Dez Mandamentos no monte Sinai?',
    options: ['Arão', 'Josué', 'Moisés', 'Abraão'],
    answer: 2,
    ref: 'Êxodo 31:18',
  },
  {
    id: 'q015',
    question: 'Qual é o último livro da Bíblia?',
    options: ['Judas', 'Apocalipse', 'Malaquias', 'Hebreus'],
    answer: 1,
    ref: 'Apocalipse 1:1',
  },
  {
    id: 'q016',
    question: 'Com quantos pães e peixes Jesus alimentou cerca de cinco mil homens?',
    options: ['5 pães e 2 peixes', '7 pães e 3 peixes', '2 pães e 5 peixes', '12 pães e 12 peixes'],
    answer: 0,
    ref: 'Mateus 14:17-21',
  },
  {
    id: 'q017',
    question: 'Quem era conhecido pela força ligada aos seus cabelos?',
    options: ['Gideão', 'Sansão', 'Baraque', 'Jefté'],
    answer: 1,
    ref: 'Juízes 16:17',
  },
  {
    id: 'q018',
    question: 'Qual rei ficou famoso pela sabedoria ao julgar o caso das duas mães?',
    options: ['Davi', 'Ezequias', 'Salomão', 'Josias'],
    answer: 2,
    ref: '1 Reis 3:16-28',
  },
  {
    id: 'q019',
    question: 'Quem foi vendido pelos irmãos e se tornou governador do Egito?',
    options: ['Benjamim', 'José', 'Judá', 'Rúben'],
    answer: 1,
    ref: 'Gênesis 41:41',
  },
  {
    id: 'q020',
    question: 'Qual profeta foi levado ao céu num redemoinho, com carro e cavalos de fogo?',
    options: ['Eliseu', 'Elias', 'Isaías', 'Ezequiel'],
    answer: 1,
    ref: '2 Reis 2:11',
  },
  {
    id: 'q021',
    question: 'Onde Jesus transformou água em vinho?',
    options: ['Caná da Galileia', 'Jericó', 'Betânia', 'Samaria'],
    answer: 0,
    ref: 'João 2:1-11',
  },
  {
    id: 'q022',
    question: 'Quem batizou Jesus?',
    options: ['Pedro', 'João Batista', 'Tiago', 'Nicodemos'],
    answer: 1,
    ref: 'Mateus 3:13',
  },
  {
    id: 'q023',
    question: 'Quantos dias Jesus jejuou no deserto?',
    options: ['7', '21', '40', '50'],
    answer: 2,
    ref: 'Mateus 4:2',
  },
  {
    id: 'q024',
    question: 'Qual casal mentiu sobre o valor de uma propriedade em Atos?',
    options: ['Áquila e Priscila', 'Ananias e Safira', 'Zacarias e Isabel', 'Booz e Rute'],
    answer: 1,
    ref: 'Atos 5:1-10',
  },
  {
    id: 'q025',
    question: 'Quem escreveu a maioria dos Salmos?',
    options: ['Salomão', 'Moisés', 'Davi', 'Asafe'],
    answer: 2,
    ref: 'Salmos (títulos)',
  },
  {
    id: 'q026',
    question: 'Qual apóstolo era coletor de impostos?',
    options: ['Mateus', 'Bartolomeu', 'Tadeu', 'Simão'],
    answer: 0,
    ref: 'Mateus 9:9',
  },
  {
    id: 'q027',
    question: 'O fruto do Espírito, em Gálatas, começa com...',
    options: ['Fé', 'Amor', 'Paz', 'Bondade'],
    answer: 1,
    ref: 'Gálatas 5:22',
  },
  {
    id: 'q028',
    question: 'Quem apareceu com Jesus na transfiguração?',
    options: ['Abraão e Davi', 'Moisés e Elias', 'Enoque e Noé', 'Isaías e Jeremias'],
    answer: 1,
    ref: 'Mateus 17:3',
  },
  {
    id: 'q029',
    question: 'Qual cidade teve os muros derrubados após sete voltas?',
    options: ['Ai', 'Jericó', 'Gaza', 'Hebrom'],
    answer: 1,
    ref: 'Josué 6:15-20',
  },
  {
    id: 'q030',
    question: 'Quem era a sogra de Rute?',
    options: ['Ana', 'Noemi', 'Débora', 'Ester'],
    answer: 1,
    ref: 'Rute 1:4',
  },
  {
    id: 'q031',
    question: 'Qual rainha arriscou a vida para salvar seu povo do decreto de Hamã?',
    options: ['Ester', 'Bate-Seba', 'Rainha de Sabá', 'Jezabel'],
    answer: 0,
    ref: 'Ester 4:16',
  },
  {
    id: 'q032',
    question: 'Quantas pragas atingiram o Egito?',
    options: ['7', '10', '12', '3'],
    answer: 1,
    ref: 'Êxodo 7-12',
  },
  {
    id: 'q033',
    question: 'Quem interpretou o sonho das vacas gordas e magras do faraó?',
    options: ['Daniel', 'Moisés', 'José', 'Arão'],
    answer: 2,
    ref: 'Gênesis 41:25-27',
  },
  {
    id: 'q034',
    question: 'Qual discípulo duvidou da ressurreição até ver as marcas dos cravos?',
    options: ['Tomé', 'Filipe', 'André', 'Natanael'],
    answer: 0,
    ref: 'João 20:25',
  },
  {
    id: 'q035',
    question: 'Em que dia da criação Deus fez o homem?',
    options: ['Terceiro', 'Quarto', 'Quinto', 'Sexto'],
    answer: 3,
    ref: 'Gênesis 1:26-31',
  },
  {
    id: 'q036',
    question: 'Qual livro vem logo depois dos quatro Evangelhos?',
    options: ['Romanos', 'Atos dos Apóstolos', 'Hebreus', 'Tiago'],
    answer: 1,
    ref: 'Ordem do NT',
  },
  {
    id: 'q037',
    question: 'Quem escreveu a carta aos Romanos?',
    options: ['Pedro', 'João', 'Paulo', 'Tiago'],
    answer: 2,
    ref: 'Romanos 1:1',
  },
  {
    id: 'q038',
    question: 'Qual era o nome de Paulo antes da conversão?',
    options: ['Silas', 'Saulo', 'Simão', 'Estêvão'],
    answer: 1,
    ref: 'Atos 13:9',
  },
  {
    id: 'q039',
    question: 'No caminho de qual cidade Paulo teve o encontro com Jesus?',
    options: ['Roma', 'Antioquia', 'Damasco', 'Corinto'],
    answer: 2,
    ref: 'Atos 9:3',
  },
  {
    id: 'q040',
    question: 'Quem foi o primeiro mártir da igreja, apedrejado em Atos?',
    options: ['Estêvão', 'Tiago', 'Barnabé', 'Marcos'],
    answer: 0,
    ref: 'Atos 7:59-60',
  },
  {
    id: 'q041',
    question: 'Qual é o versículo conhecido como "o evangelho em resumo"?',
    options: ['Salmos 23:1', 'João 3:16', 'Mateus 5:1', 'Romanos 12:1'],
    answer: 1,
    ref: 'João 3:16',
  },
  {
    id: 'q042',
    question: '"O Senhor é o meu pastor..." — o que vem a seguir?',
    options: ['e me guarda do mal', 'nada me faltará', 'e me dá descanso', 'para todo o sempre'],
    answer: 1,
    ref: 'Salmos 23:1',
  },
  {
    id: 'q043',
    question: 'Quem subiu num sicômoro para ver Jesus?',
    options: ['Bartimeu', 'Zaqueu', 'Lázaro', 'Nicodemos'],
    answer: 1,
    ref: 'Lucas 19:4',
  },
  {
    id: 'q044',
    question: 'Qual amigo de Jesus foi ressuscitado depois de quatro dias no túmulo?',
    options: ['Lázaro', 'Jairo', 'Estêvão', 'Timóteo'],
    answer: 0,
    ref: 'João 11:39-44',
  },
  {
    id: 'q045',
    question: 'Quantos anos Israel andou no deserto?',
    options: ['7', '12', '40', '70'],
    answer: 2,
    ref: 'Números 14:33-34',
  },
  {
    id: 'q046',
    question: 'Quem sucedeu Moisés na liderança de Israel?',
    options: ['Calebe', 'Josué', 'Arão', 'Eleazar'],
    answer: 1,
    ref: 'Josué 1:1-2',
  },
  {
    id: 'q047',
    question: 'Qual profeta confrontou os profetas de Baal no monte Carmelo?',
    options: ['Eliseu', 'Elias', 'Miqueias', 'Naum'],
    answer: 1,
    ref: '1 Reis 18:20-40',
  },
  {
    id: 'q048',
    question: 'O que caiu do céu para alimentar Israel no deserto?',
    options: ['Trigo', 'Maná', 'Mel', 'Cevada'],
    answer: 1,
    ref: 'Êxodo 16:14-15',
  },
  {
    id: 'q049',
    question: 'Qual é o maior capítulo da Bíblia?',
    options: ['Salmos 119', 'Salmos 23', 'Isaías 53', 'Gênesis 1'],
    answer: 0,
    ref: 'Salmos 119 (176 versículos)',
  },
  {
    id: 'q050',
    question: 'Quem lavou as mãos ao entregar Jesus para a crucificação?',
    options: ['Herodes', 'Pilatos', 'Caifás', 'Anás'],
    answer: 1,
    ref: 'Mateus 27:24',
  },
  {
    id: 'q051',
    question: 'Quantas cartas Paulo escreveu para a igreja de Corinto (no cânon)?',
    options: ['1', '2', '3', '4'],
    answer: 1,
    ref: '1 e 2 Coríntios',
  },
  {
    id: 'q052',
    question: 'Qual mulher juíza liderou Israel na vitória contra Sísera?',
    options: ['Débora', 'Míriam', 'Hulda', 'Abigail'],
    answer: 0,
    ref: 'Juízes 4:4-9',
  },
  {
    id: 'q053',
    question: 'Onde os discípulos foram chamados de cristãos pela primeira vez?',
    options: ['Jerusalém', 'Antioquia', 'Éfeso', 'Roma'],
    answer: 1,
    ref: 'Atos 11:26',
  },
  {
    id: 'q054',
    question: 'Qual anjo anunciou a Maria o nascimento de Jesus?',
    options: ['Miguel', 'Gabriel', 'Rafael', 'Um serafim'],
    answer: 1,
    ref: 'Lucas 1:26-31',
  },
  {
    id: 'q055',
    question: 'Quem pediu a cabeça de João Batista?',
    options: ['A filha de Herodias', 'Jezabel', 'Salomé de Betânia', 'A mulher de Pilatos'],
    answer: 0,
    ref: 'Marcos 6:24-25',
  },
  {
    id: 'q056',
    question: 'Qual o nome dos primeiros filhos de Adão e Eva citados na Bíblia?',
    options: ['Caim e Abel', 'Sem e Cam', 'Esaú e Jacó', 'Efraim e Manassés'],
    answer: 0,
    ref: 'Gênesis 4:1-2',
  },
  {
    id: 'q057',
    question: 'Qual apóstolo escreveu o Apocalipse?',
    options: ['Paulo', 'Pedro', 'João', 'Judas'],
    answer: 2,
    ref: 'Apocalipse 1:1,9',
  },
  {
    id: 'q058',
    question: 'O que Jesus fez na última ceia antes de partir o pão?',
    options: ['Cantou um salmo', 'Deu graças', 'Lavou o cálice', 'Leu as Escrituras'],
    answer: 1,
    ref: 'Lucas 22:19',
  },
  {
    id: 'q059',
    question: 'Quantos livros tem a Bíblia (cânon protestante)?',
    options: ['66', '72', '39', '27'],
    answer: 0,
    ref: 'AT 39 + NT 27',
  },
  {
    id: 'q060',
    question: 'Em qual monte Jesus foi crucificado, segundo os Evangelhos?',
    options: ['Sinai', 'Gólgota', 'Nebo', 'Hermon'],
    answer: 1,
    ref: 'João 19:17-18',
  },
];
