/**
 * Banco de perguntas da Arena Bíblica.
 *
 * REGRAS:
 * - `answer` é o índice da alternativa correta e NUNCA sai do servidor.
 * - `ref` aparece para o membro depois de responder (aprendizado > pontuação).
 * - Perguntas factuais e sem ambiguidade doutrinária, conferíveis no texto.
 * - Os ids são estáveis: mudar um id órfã as respostas já registradas.
 */
export interface ArenaQuestion {
  id: string;
  question: string;
  options: [string, string, string, string];
  answer: 0 | 1 | 2 | 3;
  ref: string;
}

export const QUESTIONS: ArenaQuestion[] = [
  {
    id: 'q001',
    question: 'Quantos dias e noites durou o dilúvio de chuva sobre a terra?',
    options: ['7', '30', '40', '100'],
    answer: 2,
    ref: 'Gênesis 7:12',
  },
  {
    id: 'q002',
    question: 'Quem foi lançado na cova dos leões?',
    options: ['Davi', 'Daniel', 'José', 'Jeremias'],
    answer: 1,
    ref: 'Daniel 6:16',
  },
  {
    id: 'q003',
    question: 'Qual é o primeiro livro da Bíblia?',
    options: ['Êxodo', 'Salmos', 'Gênesis', 'Mateus'],
    answer: 2,
    ref: 'Gênesis 1:1',
  },
  {
    id: 'q004',
    question: 'Quem construiu a arca?',
    options: ['Moisés', 'Abraão', 'Noé', 'Salomão'],
    answer: 2,
    ref: 'Gênesis 6:13-14',
  },
  {
    id: 'q005',
    question: 'Quantos livros tem o Novo Testamento?',
    options: ['27', '39', '66', '12'],
    answer: 0,
    ref: 'Cânon do NT',
  },
  {
    id: 'q006',
    question: 'Quem traiu Jesus por trinta moedas de prata?',
    options: ['Pedro', 'Tomé', 'Judas Iscariotes', 'João'],
    answer: 2,
    ref: 'Mateus 26:14-15',
  },
  {
    id: 'q007',
    question: 'Em que cidade Jesus nasceu?',
    options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'],
    answer: 2,
    ref: 'Mateus 2:1',
  },
  {
    id: 'q008',
    question: 'Quem derrotou o gigante Golias?',
    options: ['Saul', 'Davi', 'Sansão', 'Josué'],
    answer: 1,
    ref: '1 Samuel 17:50',
  },
  {
    id: 'q009',
    question: 'Qual apóstolo negou Jesus três vezes?',
    options: ['Pedro', 'André', 'Tiago', 'Filipe'],
    answer: 0,
    ref: 'Lucas 22:61',
  },
  {
    id: 'q010',
    question: 'Qual mar Moisés atravessou com o povo de Israel em seco?',
    options: ['Mar da Galileia', 'Mar Morto', 'Mar Vermelho', 'Mar Mediterrâneo'],
    answer: 2,
    ref: 'Êxodo 14:21-22',
  },
  {
    id: 'q011',
    question: 'Quantos discípulos Jesus escolheu como apóstolos?',
    options: ['7', '10', '12', '70'],
    answer: 2,
    ref: 'Lucas 6:13',
  },
  {
    id: 'q012',
    question: 'Quem foi engolido por um grande peixe?',
    options: ['Elias', 'Jonas', 'Amós', 'Oseias'],
    answer: 1,
    ref: 'Jonas 1:17',
  },
  {
    id: 'q013',
    question: 'Qual era o ofício de Jesus antes do ministério?',
    options: ['Pescador', 'Carpinteiro', 'Pastor de ovelhas', 'Coletor de impostos'],
    answer: 1,
    ref: 'Marcos 6:3',
  },
  {
    id: 'q014',
    question: 'Quem recebeu as tábuas dos Dez Mandamentos no monte Sinai?',
    options: ['Arão', 'Josué', 'Moisés', 'Abraão'],
    answer: 2,
    ref: 'Êxodo 31:18',
  },
  {
    id: 'q015',
    question: 'Qual é o último livro da Bíblia?',
    options: ['Judas', 'Apocalipse', 'Malaquias', 'Hebreus'],
    answer: 1,
    ref: 'Apocalipse 1:1',
  },
  {
    id: 'q016',
    question: 'Com quantos pães e peixes Jesus alimentou cerca de cinco mil homens?',
    options: ['5 pães e 2 peixes', '7 pães e 3 peixes', '2 pães e 5 peixes', '12 pães e 12 peixes'],
    answer: 0,
    ref: 'Mateus 14:17-21',
  },
  {
    id: 'q017',
    question: 'Quem era conhecido pela força ligada aos seus cabelos?',
    options: ['Gideão', 'Sansão', 'Baraque', 'Jefté'],
    answer: 1,
    ref: 'Juízes 16:17',
  },
  {
    id: 'q018',
    question: 'Qual rei ficou famoso pela sabedoria ao julgar o caso das duas mães?',
    options: ['Davi', 'Ezequias', 'Salomão', 'Josias'],
    answer: 2,
    ref: '1 Reis 3:16-28',
  },
  {
    id: 'q019',
    question: 'Quem foi vendido pelos irmãos e se tornou governador do Egito?',
    options: ['Benjamim', 'José', 'Judá', 'Rúben'],
    answer: 1,
    ref: 'Gênesis 41:41',
  },
  {
    id: 'q020',
    question: 'Qual profeta foi levado ao céu num redemoinho, com carro e cavalos de fogo?',
    options: ['Eliseu', 'Elias', 'Isaías', 'Ezequiel'],
    answer: 1,
    ref: '2 Reis 2:11',
  },
  {
    id: 'q021',
    question: 'Onde Jesus transformou água em vinho?',
    options: ['Caná da Galileia', 'Jericó', 'Betânia', 'Samaria'],
    answer: 0,
    ref: 'João 2:1-11',
  },
  {
    id: 'q022',
    question: 'Quem batizou Jesus?',
    options: ['Pedro', 'João Batista', 'Tiago', 'Nicodemos'],
    answer: 1,
    ref: 'Mateus 3:13',
  },
  {
    id: 'q023',
    question: 'Quantos dias Jesus jejuou no deserto?',
    options: ['7', '21', '40', '50'],
    answer: 2,
    ref: 'Mateus 4:2',
  },
  {
    id: 'q024',
    question: 'Qual casal mentiu sobre o valor de uma propriedade em Atos?',
    options: ['Áquila e Priscila', 'Ananias e Safira', 'Zacarias e Isabel', 'Booz e Rute'],
    answer: 1,
    ref: 'Atos 5:1-10',
  },
  {
    id: 'q025',
    question: 'Quem escreveu a maioria dos Salmos?',
    options: ['Salomão', 'Moisés', 'Davi', 'Asafe'],
    answer: 2,
    ref: 'Salmos (títulos)',
  },
  {
    id: 'q026',
    question: 'Qual apóstolo era coletor de impostos?',
    options: ['Mateus', 'Bartolomeu', 'Tadeu', 'Simão'],
    answer: 0,
    ref: 'Mateus 9:9',
  },
  {
    id: 'q027',
    question: 'O fruto do Espírito, em Gálatas, começa com...',
    options: ['Fé', 'Amor', 'Paz', 'Bondade'],
    answer: 1,
    ref: 'Gálatas 5:22',
  },
  {
    id: 'q028',
    question: 'Quem apareceu com Jesus na transfiguração?',
    options: ['Abraão e Davi', 'Moisés e Elias', 'Enoque e Noé', 'Isaías e Jeremias'],
    answer: 1,
    ref: 'Mateus 17:3',
  },
  {
    id: 'q029',
    question: 'Qual cidade teve os muros derrubados após sete voltas?',
    options: ['Ai', 'Jericó', 'Gaza', 'Hebrom'],
    answer: 1,
    ref: 'Josué 6:15-20',
  },
  {
    id: 'q030',
    question: 'Quem era a sogra de Rute?',
    options: ['Ana', 'Noemi', 'Débora', 'Ester'],
    answer: 1,
    ref: 'Rute 1:4',
  },
  {
    id: 'q031',
    question: 'Qual rainha arriscou a vida para salvar seu povo do decreto de Hamã?',
    options: ['Ester', 'Bate-Seba', 'Rainha de Sabá', 'Jezabel'],
    answer: 0,
    ref: 'Ester 4:16',
  },
  {
    id: 'q032',
    question: 'Quantas pragas atingiram o Egito?',
    options: ['7', '10', '12', '3'],
    answer: 1,
    ref: 'Êxodo 7-12',
  },
  {
    id: 'q033',
    question: 'Quem interpretou o sonho das vacas gordas e magras do faraó?',
    options: ['Daniel', 'Moisés', 'José', 'Arão'],
    answer: 2,
    ref: 'Gênesis 41:25-27',
  },
  {
    id: 'q034',
    question: 'Qual discípulo duvidou da ressurreição até ver as marcas dos cravos?',
    options: ['Tomé', 'Filipe', 'André', 'Natanael'],
    answer: 0,
    ref: 'João 20:25',
  },
  {
    id: 'q035',
    question: 'Em que dia da criação Deus fez o homem?',
    options: ['Terceiro', 'Quarto', 'Quinto', 'Sexto'],
    answer: 3,
    ref: 'Gênesis 1:26-31',
  },
  {
    id: 'q036',
    question: 'Qual livro vem logo depois dos quatro Evangelhos?',
    options: ['Romanos', 'Atos dos Apóstolos', 'Hebreus', 'Tiago'],
    answer: 1,
    ref: 'Ordem do NT',
  },
  {
    id: 'q037',
    question: 'Quem escreveu a carta aos Romanos?',
    options: ['Pedro', 'João', 'Paulo', 'Tiago'],
    answer: 2,
    ref: 'Romanos 1:1',
  },
  {
    id: 'q038',
    question: 'Qual era o nome de Paulo antes da conversão?',
    options: ['Silas', 'Saulo', 'Simão', 'Estêvão'],
    answer: 1,
    ref: 'Atos 13:9',
  },
  {
    id: 'q039',
    question: 'No caminho de qual cidade Paulo teve o encontro com Jesus?',
    options: ['Roma', 'Antioquia', 'Damasco', 'Corinto'],
    answer: 2,
    ref: 'Atos 9:3',
  },
  {
    id: 'q040',
    question: 'Quem foi o primeiro mártir da igreja, apedrejado em Atos?',
    options: ['Estêvão', 'Tiago', 'Barnabé', 'Marcos'],
    answer: 0,
    ref: 'Atos 7:59-60',
  },
  {
    id: 'q041',
    question: 'Qual é o versículo conhecido como "o evangelho em resumo"?',
    options: ['Salmos 23:1', 'João 3:16', 'Mateus 5:1', 'Romanos 12:1'],
    answer: 1,
    ref: 'João 3:16',
  },
  {
    id: 'q042',
    question: '"O Senhor é o meu pastor..." — o que vem a seguir?',
    options: ['e me guarda do mal', 'nada me faltará', 'e me dá descanso', 'para todo o sempre'],
    answer: 1,
    ref: 'Salmos 23:1',
  },
  {
    id: 'q043',
    question: 'Quem subiu num sicômoro para ver Jesus?',
    options: ['Bartimeu', 'Zaqueu', 'Lázaro', 'Nicodemos'],
    answer: 1,
    ref: 'Lucas 19:4',
  },
  {
    id: 'q044',
    question: 'Qual amigo de Jesus foi ressuscitado depois de quatro dias no túmulo?',
    options: ['Lázaro', 'Jairo', 'Estêvão', 'Timóteo'],
    answer: 0,
    ref: 'João 11:39-44',
  },
  {
    id: 'q045',
    question: 'Quantos anos Israel andou no deserto?',
    options: ['7', '12', '40', '70'],
    answer: 2,
    ref: 'Números 14:33-34',
  },
  {
    id: 'q046',
    question: 'Quem sucedeu Moisés na liderança de Israel?',
    options: ['Calebe', 'Josué', 'Arão', 'Eleazar'],
    answer: 1,
    ref: 'Josué 1:1-2',
  },
  {
    id: 'q047',
    question: 'Qual profeta confrontou os profetas de Baal no monte Carmelo?',
    options: ['Eliseu', 'Elias', 'Miqueias', 'Naum'],
    answer: 1,
    ref: '1 Reis 18:20-40',
  },
  {
    id: 'q048',
    question: 'O que caiu do céu para alimentar Israel no deserto?',
    options: ['Trigo', 'Maná', 'Mel', 'Cevada'],
    answer: 1,
    ref: 'Êxodo 16:14-15',
  },
  {
    id: 'q049',
    question: 'Qual é o maior capítulo da Bíblia?',
    options: ['Salmos 119', 'Salmos 23', 'Isaías 53', 'Gênesis 1'],
    answer: 0,
    ref: 'Salmos 119 (176 versículos)',
  },
  {
    id: 'q050',
    question: 'Quem lavou as mãos ao entregar Jesus para a crucificação?',
    options: ['Herodes', 'Pilatos', 'Caifás', 'Anás'],
    answer: 1,
    ref: 'Mateus 27:24',
  },
  {
    id: 'q051',
    question: 'Quantas cartas Paulo escreveu para a igreja de Corinto (no cânon)?',
    options: ['1', '2', '3', '4'],
    answer: 1,
    ref: '1 e 2 Coríntios',
  },
  {
    id: 'q052',
    question: 'Qual mulher juíza liderou Israel na vitória contra Sísera?',
    options: ['Débora', 'Míriam', 'Hulda', 'Abigail'],
    answer: 0,
    ref: 'Juízes 4:4-9',
  },
  {
    id: 'q053',
    question: 'Onde os discípulos foram chamados de cristãos pela primeira vez?',
    options: ['Jerusalém', 'Antioquia', 'Éfeso', 'Roma'],
    answer: 1,
    ref: 'Atos 11:26',
  },
  {
    id: 'q054',
    question: 'Qual anjo anunciou a Maria o nascimento de Jesus?',
    options: ['Miguel', 'Gabriel', 'Rafael', 'Um serafim'],
    answer: 1,
    ref: 'Lucas 1:26-31',
  },
  {
    id: 'q055',
    question: 'Quem pediu a cabeça de João Batista?',
    options: ['A filha de Herodias', 'Jezabel', 'Salomé de Betânia', 'A mulher de Pilatos'],
    answer: 0,
    ref: 'Marcos 6:24-25',
  },
  {
    id: 'q056',
    question: 'Qual o nome dos primeiros filhos de Adão e Eva citados na Bíblia?',
    options: ['Caim e Abel', 'Sem e Cam', 'Esaú e Jacó', 'Efraim e Manassés'],
    answer: 0,
    ref: 'Gênesis 4:1-2',
  },
  {
    id: 'q057',
    question: 'Qual apóstolo escreveu o Apocalipse?',
    options: ['Paulo', 'Pedro', 'João', 'Judas'],
    answer: 2,
    ref: 'Apocalipse 1:1,9',
  },
  {
    id: 'q058',
    question: 'O que Jesus fez na última ceia antes de partir o pão?',
    options: ['Cantou um salmo', 'Deu graças', 'Lavou o cálice', 'Leu as Escrituras'],
    answer: 1,
    ref: 'Lucas 22:19',
  },
  {
    id: 'q059',
    question: 'Quantos livros tem a Bíblia (cânon protestante)?',
    options: ['66', '72', '39', '27'],
    answer: 0,
    ref: 'AT 39 + NT 27',
  },
  {
    id: 'q060',
    question: 'Em qual monte Jesus foi crucificado, segundo os Evangelhos?',
    options: ['Sinai', 'Gólgota', 'Nebo', 'Hermon'],
    answer: 1,
    ref: 'João 19:17-18',
  },
  {
    id: "q061",
    question: "Em quantos dias Deus fez a obra da criação, antes de descansar?",
    options: ["3", "6", "7", "12"],
    answer: 1,
    ref: "Gênesis 2:2",
  },
  {
    id: "q062",
    question: "De que parte de Adão Deus formou a mulher?",
    options: ["Do pó", "Da costela", "Do coração", "Do sopro"],
    answer: 1,
    ref: "Gênesis 2:22",
  },
  {
    id: "q063",
    question: "Que animal enganou Eva no jardim do Éden?",
    options: ["O leão", "A serpente", "O corvo", "O bode"],
    answer: 1,
    ref: "Gênesis 3:1",
  },
  {
    id: "q064",
    question: "Quem andou com Deus e foi levado sem ver a morte, antes do dilúvio?",
    options: ["Noé", "Enoque", "Elias", "Matusalém"],
    answer: 1,
    ref: "Gênesis 5:24",
  },
  {
    id: "q065",
    question: "Quem foi o homem mais longevo da Bíblia, com 969 anos?",
    options: ["Adão", "Noé", "Matusalém", "Abraão"],
    answer: 2,
    ref: "Gênesis 5:27",
  },
  {
    id: "q066",
    question: "Que sinal Deus deu na aliança de nunca mais destruir a terra com dilúvio?",
    options: ["Uma estrela", "O arco-íris", "Uma pomba", "Uma coluna de fogo"],
    answer: 1,
    ref: "Gênesis 9:13",
  },
  {
    id: "q067",
    question: "Em que construção Deus confundiu as línguas dos homens?",
    options: ["No templo de Salomão", "Na torre de Babel", "Nas muralhas de Jericó", "No palácio do faraó"],
    answer: 1,
    ref: "Gênesis 11:7-9",
  },
  {
    id: "q068",
    question: "De que terra Abraão saiu quando Deus o chamou?",
    options: ["Ur dos caldeus", "Egito", "Canaã", "Nínive"],
    answer: 0,
    ref: "Gênesis 11:31; 15:7",
  },
  {
    id: "q069",
    question: "O que significa o nome Isaque?",
    options: ["Presente", "Riso", "Promessa", "Amado"],
    answer: 1,
    ref: "Gênesis 21:6",
  },
  {
    id: "q070",
    question: "Quem se casou com Rebeca?",
    options: ["Jacó", "Esaú", "Isaque", "José"],
    answer: 2,
    ref: "Gênesis 24:67",
  },
  {
    id: "q071",
    question: "Por qual prato Esaú vendeu a primogenitura?",
    options: ["Pão e vinho", "Um guisado de lentilhas", "Peixe assado", "Mel silvestre"],
    answer: 1,
    ref: "Gênesis 25:34",
  },
  {
    id: "q072",
    question: "O que Jacó viu em sonho na noite em Betel?",
    options: ["Uma sarça em chamas", "Uma escada que tocava o céu", "Um carro de fogo", "Sete vacas gordas"],
    answer: 1,
    ref: "Gênesis 28:12",
  },
  {
    id: "q073",
    question: "Que novo nome Jacó recebeu depois de lutar até o amanhecer?",
    options: ["Israel", "Edom", "Efraim", "Jesurum"],
    answer: 0,
    ref: "Gênesis 32:28",
  },
  {
    id: "q074",
    question: "Quantos filhos homens teve Jacó?",
    options: ["7", "10", "12", "14"],
    answer: 2,
    ref: "Gênesis 35:22-26",
  },
  {
    id: "q075",
    question: "Que presente José ganhou de seu pai, despertando a inveja dos irmãos?",
    options: ["Um anel de ouro", "Uma túnica colorida", "Um cajado", "Um rebanho"],
    answer: 1,
    ref: "Gênesis 37:3",
  },
  {
    id: "q076",
    question: "Por quantas moedas de prata José foi vendido pelos irmãos?",
    options: ["10", "20", "30", "50"],
    answer: 1,
    ref: "Gênesis 37:28",
  },
  {
    id: "q077",
    question: "Na casa de quem José serviu no Egito antes de ser preso?",
    options: ["Do faraó", "De Potifar", "De Arioque", "De Hirão"],
    answer: 1,
    ref: "Gênesis 39:1",
  },
  {
    id: "q078",
    question: "Qual era o irmão mais novo de José?",
    options: ["Rúben", "Judá", "Benjamim", "Simeão"],
    answer: 2,
    ref: "Gênesis 42:13",
  },
  {
    id: "q079",
    question: "Onde a mãe de Moisés o escondeu para salvá-lo?",
    options: ["Numa caverna", "Num cesto no rio Nilo", "Num celeiro", "No templo"],
    answer: 1,
    ref: "Êxodo 2:3",
  },
  {
    id: "q080",
    question: "Quem vigiava de longe o cesto do bebê Moisés?",
    options: ["Sua irmã Miriã", "Zípora", "Ana", "Débora"],
    answer: 0,
    ref: "Êxodo 2:4",
  },
  {
    id: "q081",
    question: "Onde Deus falou com Moisés pela primeira vez?",
    options: ["No monte Nebo", "Na sarça ardente", "No tabernáculo", "No rio Jordão"],
    answer: 1,
    ref: "Êxodo 3:2-4",
  },
  {
    id: "q082",
    question: "Que nome Deus revelou a Moisés na sarça?",
    options: ["El Shaday", "EU SOU O QUE SOU", "Emanuel", "O Ancião de Dias"],
    answer: 1,
    ref: "Êxodo 3:14",
  },
  {
    id: "q083",
    question: "Quem falava por Moisés diante do faraó?",
    options: ["Josué", "Arão", "Hur", "Calebe"],
    answer: 1,
    ref: "Êxodo 4:14-16",
  },
  {
    id: "q084",
    question: "Qual foi a primeira praga do Egito?",
    options: ["Rãs", "Trevas", "Águas em sangue", "Gafanhotos"],
    answer: 2,
    ref: "Êxodo 7:20",
  },
  {
    id: "q085",
    question: "Qual foi a última praga do Egito?",
    options: ["Trevas", "Saraiva", "Morte dos primogênitos", "Úlceras"],
    answer: 2,
    ref: "Êxodo 12:29",
  },
  {
    id: "q086",
    question: "O que os israelitas passaram nos umbrais das portas na primeira Páscoa?",
    options: ["Azeite", "Sangue do cordeiro", "Água", "Mirra"],
    answer: 1,
    ref: "Êxodo 12:7",
  },
  {
    id: "q087",
    question: "Quantos dias Moisés ficou no monte Sinai recebendo a lei?",
    options: ["7", "21", "40", "70"],
    answer: 2,
    ref: "Êxodo 24:18",
  },
  {
    id: "q088",
    question: "Que ídolo Arão fez enquanto Moisés estava no monte?",
    options: ["Uma serpente de bronze", "Um bezerro de ouro", "Uma estátua do faraó", "Um poste-ídolo"],
    answer: 1,
    ref: "Êxodo 32:4",
  },
  {
    id: "q089",
    question: "Onde eram guardadas as tábuas da lei?",
    options: ["Sobre o altar", "Na arca da aliança", "No candelabro", "Na tenda de Arão"],
    answer: 1,
    ref: "Êxodo 40:20",
  },
  {
    id: "q090",
    question: "Quantos espias Moisés enviou para reconhecer Canaã?",
    options: ["2", "10", "12", "40"],
    answer: 2,
    ref: "Números 13:1-16",
  },
  {
    id: "q091",
    question: "Quais espias creram que Israel podia conquistar a terra?",
    options: ["Josué e Calebe", "Arão e Hur", "Eldade e Medade", "Datã e Abirão"],
    answer: 0,
    ref: "Números 14:6-9",
  },
  {
    id: "q092",
    question: "O que Moisés levantou no deserto para curar os mordidos pelas serpentes?",
    options: ["Uma cruz de madeira", "Uma serpente de bronze", "Um estandarte de linho", "Uma vara de amendoeira"],
    answer: 1,
    ref: "Números 21:9",
  },
  {
    id: "q093",
    question: "Que animal falou com o profeta Balaão?",
    options: ["Um corvo", "Uma jumenta", "Um leão", "Um cordeiro"],
    answer: 1,
    ref: "Números 22:28",
  },
  {
    id: "q094",
    question: "De que monte Moisés avistou a terra prometida?",
    options: ["Sinai", "Carmelo", "Nebo", "Hermom"],
    answer: 2,
    ref: "Deuteronômio 34:1",
  },
  {
    id: "q095",
    question: "Quem escondeu os espias israelitas em Jericó?",
    options: ["Débora", "Raabe", "Rute", "Jael"],
    answer: 1,
    ref: "Josué 2:1-6",
  },
  {
    id: "q096",
    question: "Que sinal Raabe pendurou na janela para ser poupada?",
    options: ["Uma lamparina", "Um cordão vermelho", "Uma bandeira branca", "Um ramo de oliveira"],
    answer: 1,
    ref: "Josué 2:18",
  },
  {
    id: "q097",
    question: "Que rio Israel atravessou em seco para entrar em Canaã?",
    options: ["Nilo", "Eufrates", "Jordão", "Quisom"],
    answer: 2,
    ref: "Josué 3:15-17",
  },
  {
    id: "q098",
    question: "Em que batalha o sol se deteve a pedido de Josué?",
    options: ["Jericó", "Ai", "Gibeom", "Megido"],
    answer: 2,
    ref: "Josué 10:12-13",
  },
  {
    id: "q099",
    question: "Com quantos homens Gideão venceu os midianitas?",
    options: ["100", "300", "1.000", "32.000"],
    answer: 1,
    ref: "Juízes 7:7",
  },
  {
    id: "q100",
    question: "No primeiro sinal que Gideão pediu, o orvalho deveria molhar...",
    options: ["A eira inteira", "Somente a lã", "As duas partes", "Nada"],
    answer: 1,
    ref: "Juízes 6:37-38",
  },
  {
    id: "q101",
    question: "A quem Sansão revelou o segredo da sua força?",
    options: ["Jael", "Dalila", "Mical", "Bate-Seba"],
    answer: 1,
    ref: "Juízes 16:17",
  },
  {
    id: "q102",
    question: "Com que arma Sansão feriu mil filisteus?",
    options: ["Uma espada", "Uma queixada de jumento", "Uma funda", "Uma lança"],
    answer: 1,
    ref: "Juízes 15:15",
  },
  {
    id: "q103",
    question: "De que povo era Rute?",
    options: ["Egípcia", "Moabita", "Filisteia", "Amonita"],
    answer: 1,
    ref: "Rute 1:4",
  },
  {
    id: "q104",
    question: "Com quem Rute se casou em Belém?",
    options: ["Elimeleque", "Boaz", "Obede", "Jessé"],
    answer: 1,
    ref: "Rute 4:13",
  },
  {
    id: "q105",
    question: "Rute foi bisavó de qual rei?",
    options: ["Saul", "Davi", "Salomão", "Ezequias"],
    answer: 1,
    ref: "Rute 4:17",
  },
  {
    id: "q106",
    question: "Que mulher orou por um filho e o entregou ao Senhor no tabernáculo?",
    options: ["Ana", "Sara", "Rebeca", "Isabel"],
    answer: 0,
    ref: "1 Samuel 1:27-28",
  },
  {
    id: "q107",
    question: "Quem foi o primeiro rei de Israel?",
    options: ["Davi", "Saul", "Salomão", "Samuel"],
    answer: 1,
    ref: "1 Samuel 10:1",
  },
  {
    id: "q108",
    question: "Que instrumento Davi tocava para acalmar o rei Saul?",
    options: ["Flauta", "Harpa", "Tamborim", "Trombeta"],
    answer: 1,
    ref: "1 Samuel 16:23",
  },
  {
    id: "q109",
    question: "Quantas pedras lisas Davi apanhou no ribeiro?",
    options: ["1", "3", "5", "7"],
    answer: 2,
    ref: "1 Samuel 17:40",
  },
  {
    id: "q110",
    question: "De que cidade era o gigante Golias?",
    options: ["Gaza", "Gate", "Asdode", "Ecrom"],
    answer: 1,
    ref: "1 Samuel 17:4",
  },
  {
    id: "q111",
    question: "Quem era o grande amigo de Davi, filho de Saul?",
    options: ["Joabe", "Jônatas", "Absalão", "Natã"],
    answer: 1,
    ref: "1 Samuel 18:1",
  },
  {
    id: "q112",
    question: "Que profeta confrontou Davi com a parábola da cordeirinha?",
    options: ["Samuel", "Natã", "Gade", "Elias"],
    answer: 1,
    ref: "2 Samuel 12:1-7",
  },
  {
    id: "q113",
    question: "Qual filho de Davi se rebelou e tentou tomar o trono?",
    options: ["Salomão", "Absalão", "Amnom", "Adonias"],
    answer: 1,
    ref: "2 Samuel 15:10",
  },
  {
    id: "q114",
    question: "O que Salomão pediu a Deus no sonho em Gibeom?",
    options: ["Riquezas", "Vida longa", "Um coração sábio", "Vitória nas guerras"],
    answer: 2,
    ref: "1 Reis 3:9",
  },
  {
    id: "q115",
    question: "Quem construiu o primeiro templo de Jerusalém?",
    options: ["Davi", "Salomão", "Esdras", "Herodes"],
    answer: 1,
    ref: "1 Reis 6:1",
  },
  {
    id: "q116",
    question: "Que rainha veio de longe para comprovar a sabedoria de Salomão?",
    options: ["Vasti", "A rainha de Sabá", "Ester", "Jezabel"],
    answer: 1,
    ref: "1 Reis 10:1",
  },
  {
    id: "q117",
    question: "Quem alimentou Elias junto ao ribeiro de Querite?",
    options: ["Anjos", "Corvos", "Uma viúva", "Pombas"],
    answer: 1,
    ref: "1 Reis 17:6",
  },
  {
    id: "q118",
    question: "O que não acabou na casa da viúva de Sarepta?",
    options: ["Pão e vinho", "Farinha e azeite", "Água e mel", "Trigo e cevada"],
    answer: 1,
    ref: "1 Reis 17:16",
  },
  {
    id: "q119",
    question: "Como Deus falou com Elias no monte Horebe?",
    options: ["No terremoto", "No fogo", "No vento forte", "Numa voz mansa e delicada"],
    answer: 3,
    ref: "1 Reis 19:12",
  },
  {
    id: "q120",
    question: "Quem pediu porção dobrada do espírito de Elias?",
    options: ["Josué", "Eliseu", "Geazi", "Obadias"],
    answer: 1,
    ref: "2 Reis 2:9",
  },
  {
    id: "q121",
    question: "Quantas vezes Naamã mergulhou no Jordão para ser curado da lepra?",
    options: ["3", "5", "7", "12"],
    answer: 2,
    ref: "2 Reis 5:14",
  },
  {
    id: "q122",
    question: "O que Eliseu fez flutuar nas águas do Jordão?",
    options: ["Uma moeda", "Um ferro de machado", "Um cajado", "Uma arca"],
    answer: 1,
    ref: "2 Reis 6:6",
  },
  {
    id: "q123",
    question: "Quantos anos de vida Deus acrescentou ao rei Ezequias?",
    options: ["5", "10", "15", "20"],
    answer: 2,
    ref: "2 Reis 20:6",
  },
  {
    id: "q124",
    question: "Quem criou Ester como filha?",
    options: ["Mardoqueu", "Hamã", "Assuero", "Boaz"],
    answer: 0,
    ref: "Ester 2:7",
  },
  {
    id: "q125",
    question: "Qual foi o fim de Hamã?",
    options: ["Fugiu para a Pérsia", "Foi pendurado na forca que preparou para Mardoqueu", "Foi exilado", "Virou servo do rei"],
    answer: 1,
    ref: "Ester 7:10",
  },
  {
    id: "q126",
    question: "Em que terra vivia Jó?",
    options: ["Uz", "Ur", "Edom", "Midiã"],
    answer: 0,
    ref: "Jó 1:1",
  },
  {
    id: "q127",
    question: "Quantos amigos vieram consolar Jó?",
    options: ["2", "3", "4", "7"],
    answer: 1,
    ref: "Jó 2:11",
  },
  {
    id: "q128",
    question: "Como terminou a história de Jó?",
    options: ["Morreu na pobreza", "O Senhor lhe deu o dobro do que tinha", "Tornou-se rei", "Mudou-se para o Egito"],
    answer: 1,
    ref: "Jó 42:10",
  },
  {
    id: "q129",
    question: "Qual é o menor capítulo da Bíblia?",
    options: ["Salmo 23", "Salmo 117", "Salmo 1", "Salmo 150"],
    answer: 1,
    ref: "Salmo 117",
  },
  {
    id: "q130",
    question: "Segundo Provérbios, o que é o princípio da sabedoria?",
    options: ["O estudo", "O temor do Senhor", "A prudência", "O bom conselho"],
    answer: 1,
    ref: "Provérbios 9:10",
  },
  {
    id: "q131",
    question: "Que capítulo de Provérbios descreve a mulher virtuosa?",
    options: ["8", "15", "22", "31"],
    answer: 3,
    ref: "Provérbios 31:10-31",
  },
  {
    id: "q132",
    question: "Que profeta viu serafins de seis asas na visão do templo?",
    options: ["Ezequiel", "Isaías", "Daniel", "Amós"],
    answer: 1,
    ref: "Isaías 6:2",
  },
  {
    id: "q133",
    question: "Com o que o serafim tocou os lábios de Isaías?",
    options: ["Água do altar", "Uma brasa viva", "Azeite", "Mel"],
    answer: 1,
    ref: "Isaías 6:6-7",
  },
  {
    id: "q134",
    question: "Que nome profético significa Deus conosco?",
    options: ["Elias", "Emanuel", "Eliseu", "Efraim"],
    answer: 1,
    ref: "Isaías 7:14",
  },
  {
    id: "q135",
    question: "Qual profeta é lembrado como o profeta que chora?",
    options: ["Isaías", "Jeremias", "Oseias", "Joel"],
    answer: 1,
    ref: "Jeremias 9:1",
  },
  {
    id: "q136",
    question: "Quem foi lançado na fornalha por não adorar a estátua do rei?",
    options: ["Sadraque, Mesaque e Abede-Nego", "Eldade, Medade e Hur", "Esdras, Neemias e Zorobabel", "Elifaz, Bildade e Zofar"],
    answer: 0,
    ref: "Daniel 3:20-23",
  },
  {
    id: "q137",
    question: "No sonho de Nabucodonosor, o que despedaçou a grande estátua?",
    options: ["Um raio", "Uma pedra", "Um exército", "Um vento"],
    answer: 1,
    ref: "Daniel 2:34",
  },
  {
    id: "q138",
    question: "Que escrita apareceu na parede durante a festa de Belsazar?",
    options: ["Maranata", "MENE, MENE, TEQUEL e PARSIM", "Efatá", "Talita cumi"],
    answer: 1,
    ref: "Daniel 5:25",
  },
  {
    id: "q139",
    question: "Quantas vezes por dia Daniel costumava orar?",
    options: ["1", "2", "3", "7"],
    answer: 2,
    ref: "Daniel 6:10",
  },
  {
    id: "q140",
    question: "Para onde Jonas tentou fugir da presença do Senhor?",
    options: ["Nínive", "Társis", "Egito", "Jope"],
    answer: 1,
    ref: "Jonas 1:3",
  },
  {
    id: "q141",
    question: "A que cidade Jonas foi enviado para pregar?",
    options: ["Babilônia", "Nínive", "Sodoma", "Tiro"],
    answer: 1,
    ref: "Jonas 1:2",
  },
  {
    id: "q142",
    question: "Que profeta anunciou que o Messias nasceria em Belém?",
    options: ["Miqueias", "Naum", "Sofonias", "Ageu"],
    answer: 0,
    ref: "Miqueias 5:2",
  },
  {
    id: "q143",
    question: "Qual é o último livro do Antigo Testamento?",
    options: ["Zacarias", "Malaquias", "Ester", "Daniel"],
    answer: 1,
    ref: "Malaquias 4",
  },
  {
    id: "q144",
    question: "Quem eram os pais de João Batista?",
    options: ["José e Maria", "Zacarias e Isabel", "Elcana e Ana", "Áquila e Priscila"],
    answer: 1,
    ref: "Lucas 1:13",
  },
  {
    id: "q145",
    question: "O que os magos ofereceram ao menino Jesus?",
    options: ["Prata, ouro e pérolas", "Ouro, incenso e mirra", "Panos, azeite e mel", "Cordeiros e pombas"],
    answer: 1,
    ref: "Mateus 2:11",
  },
  {
    id: "q146",
    question: "Para onde José fugiu com Maria e o menino Jesus?",
    options: ["Nazaré", "Egito", "Babilônia", "Damasco"],
    answer: 1,
    ref: "Mateus 2:14",
  },
  {
    id: "q147",
    question: "Em que cidade Jesus cresceu?",
    options: ["Belém", "Jerusalém", "Nazaré", "Cafarnaum"],
    answer: 2,
    ref: "Lucas 2:39-40",
  },
  {
    id: "q148",
    question: "Com quantos anos Jesus foi encontrado no templo entre os mestres?",
    options: ["8", "12", "18", "30"],
    answer: 1,
    ref: "Lucas 2:42-46",
  },
  {
    id: "q149",
    question: "O que João Batista comia no deserto?",
    options: ["Pão e peixe", "Gafanhotos e mel silvestre", "Frutas e raízes", "Maná"],
    answer: 1,
    ref: "Mateus 3:4",
  },
  {
    id: "q150",
    question: "Em que rio Jesus foi batizado?",
    options: ["Nilo", "Jordão", "Eufrates", "Quisom"],
    answer: 1,
    ref: "Mateus 3:13",
  },
  {
    id: "q151",
    question: "Em forma de que o Espírito Santo desceu no batismo de Jesus?",
    options: ["Fogo", "Pomba", "Vento", "Nuvem"],
    answer: 1,
    ref: "Mateus 3:16",
  },
  {
    id: "q152",
    question: "Com que palavras Jesus respondia às tentações no deserto?",
    options: ["Está escrito", "Eu sou", "Aqui estou", "Seja feito"],
    answer: 0,
    ref: "Mateus 4:4",
  },
  {
    id: "q153",
    question: "Que apelido Jesus deu aos irmãos Tiago e João?",
    options: ["Filhos da luz", "Filhos do trovão", "Colunas da igreja", "Pescadores de homens"],
    answer: 1,
    ref: "Marcos 3:17",
  },
  {
    id: "q154",
    question: "Que nome Jesus deu a Simão, irmão de André?",
    options: ["Justo", "Pedro", "Barnabé", "Boanerges"],
    answer: 1,
    ref: "João 1:42",
  },
  {
    id: "q155",
    question: "Onde Jesus pregou o sermão das bem-aventuranças?",
    options: ["No barco", "No monte", "No templo", "No deserto"],
    answer: 1,
    ref: "Mateus 5:1",
  },
  {
    id: "q156",
    question: "Vós sois o ___ da terra, disse Jesus.",
    options: ["Luz", "Sal", "Fermento", "Trigo"],
    answer: 1,
    ref: "Mateus 5:13",
  },
  {
    id: "q157",
    question: "Na parábola, o homem prudente construiu a casa sobre...",
    options: ["A areia", "A rocha", "O monte", "O vale"],
    answer: 1,
    ref: "Mateus 7:24",
  },
  {
    id: "q158",
    question: "Quantos cestos sobraram na multiplicação dos cinco pães?",
    options: ["5", "7", "12", "40"],
    answer: 2,
    ref: "Mateus 14:20",
  },
  {
    id: "q159",
    question: "Qual discípulo andou sobre as águas ao encontro de Jesus?",
    options: ["João", "Pedro", "Tiago", "André"],
    answer: 1,
    ref: "Mateus 14:29",
  },
  {
    id: "q160",
    question: "Quantas ovelhas o pastor deixou para buscar a que se perdeu?",
    options: ["10", "70", "99", "100"],
    answer: 2,
    ref: "Lucas 15:4",
  },
  {
    id: "q161",
    question: "No auge da fome, que comida o filho pródigo desejou?",
    options: ["O pão dos servos", "A comida dos porcos", "Mel silvestre", "Uvas da vinha"],
    answer: 1,
    ref: "Lucas 15:16",
  },
  {
    id: "q162",
    question: "O que o pai mandou trazer para o filho pródigo que voltou?",
    options: ["Uma vara", "O melhor traje, um anel e sandálias", "Uma carta de perdão", "Uma nova herança"],
    answer: 1,
    ref: "Lucas 15:22",
  },
  {
    id: "q163",
    question: "Na parábola, quem socorreu o homem ferido na estrada de Jericó?",
    options: ["Um sacerdote", "Um levita", "Um samaritano", "Um fariseu"],
    answer: 2,
    ref: "Lucas 10:33",
  },
  {
    id: "q164",
    question: "Dos dez leprosos curados, quantos voltaram para agradecer?",
    options: ["1", "2", "5", "10"],
    answer: 0,
    ref: "Lucas 17:15-16",
  },
  {
    id: "q165",
    question: "Qual é o versículo mais curto da Bíblia em muitas traduções?",
    options: ["Orai sem cessar", "Jesus chorou", "Deus é amor", "Vigiai e orai"],
    answer: 1,
    ref: "João 11:35",
  },
  {
    id: "q166",
    question: "Que cego de Jericó clamou: Jesus, Filho de Davi?",
    options: ["Barnabé", "Bartimeu", "Bartolomeu", "Barsabás"],
    answer: 1,
    ref: "Marcos 10:46-47",
  },
  {
    id: "q167",
    question: "Montado em que animal Jesus entrou em Jerusalém?",
    options: ["Num cavalo", "Num jumentinho", "Num camelo", "Em nenhum, entrou a pé"],
    answer: 1,
    ref: "Mateus 21:7",
  },
  {
    id: "q168",
    question: "O que a viúva pobre ofertou no gazofilácio do templo?",
    options: ["Um denário", "Duas pequenas moedas", "Um talento", "Um anel"],
    answer: 1,
    ref: "Marcos 12:42",
  },
  {
    id: "q169",
    question: "Em que jardim Jesus orou antes de ser preso?",
    options: ["Gólgota", "Getsêmani", "Betânia", "Éden"],
    answer: 1,
    ref: "Mateus 26:36",
  },
  {
    id: "q170",
    question: "Que servo teve a orelha cortada por Pedro?",
    options: ["Malco", "Marcos", "Mateus", "Manaém"],
    answer: 0,
    ref: "João 18:10",
  },
  {
    id: "q171",
    question: "Que preso foi solto pela multidão no lugar de Jesus?",
    options: ["Barnabé", "Barrabás", "Bartimeu", "Silas"],
    answer: 1,
    ref: "Mateus 27:26",
  },
  {
    id: "q172",
    question: "Quem foi obrigado a carregar a cruz de Jesus?",
    options: ["Simão Pedro", "Simão de Cirene", "José de Arimateia", "Nicodemos"],
    answer: 1,
    ref: "Mateus 27:32",
  },
  {
    id: "q173",
    question: "O que significa Gólgota?",
    options: ["Monte santo", "Lugar da Caveira", "Campo de sangue", "Porta estreita"],
    answer: 1,
    ref: "Mateus 27:33",
  },
  {
    id: "q174",
    question: "O que se rasgou de alto a baixo quando Jesus morreu?",
    options: ["O altar", "O véu do templo", "As portas da cidade", "O manto do sumo sacerdote"],
    answer: 1,
    ref: "Mateus 27:51",
  },
  {
    id: "q175",
    question: "Quem cedeu o próprio túmulo para sepultar Jesus?",
    options: ["Nicodemos", "José de Arimateia", "Lázaro", "Cleopas"],
    answer: 1,
    ref: "Mateus 27:57-60",
  },
  {
    id: "q176",
    question: "Quem foi ao túmulo de madrugada e o encontrou vazio, em João 20?",
    options: ["Pedro", "Maria Madalena", "João", "Salomé"],
    answer: 1,
    ref: "João 20:1",
  },
  {
    id: "q177",
    question: "Para que povoado caminhavam os dois discípulos quando Jesus se juntou a eles?",
    options: ["Betânia", "Emaús", "Jericó", "Caná"],
    answer: 1,
    ref: "Lucas 24:13",
  },
  {
    id: "q178",
    question: "Quantos peixes foram contados na pesca depois da ressurreição?",
    options: ["12", "77", "153", "500"],
    answer: 2,
    ref: "João 21:11",
  },
  {
    id: "q179",
    question: "O que Jesus perguntou três vezes a Pedro à beira do mar?",
    options: ["Quem dizes que eu sou?", "Tu me amas?", "Onde estavas?", "Por que duvidaste?"],
    answer: 1,
    ref: "João 21:15-17",
  },
  {
    id: "q180",
    question: "De que monte Jesus subiu ao céu?",
    options: ["Sinai", "Monte das Oliveiras", "Carmelo", "Tabor"],
    answer: 1,
    ref: "Atos 1:9-12",
  },
  {
    id: "q181",
    question: "Quem foi escolhido para ocupar o lugar de Judas entre os doze?",
    options: ["Barsabás", "Matias", "Barnabé", "Estêvão"],
    answer: 1,
    ref: "Atos 1:26",
  },
  {
    id: "q182",
    question: "O que pousou sobre cada um dos discípulos no Pentecostes?",
    options: ["Pombas", "Línguas como de fogo", "Coroas", "Orvalho"],
    answer: 1,
    ref: "Atos 2:3",
  },
  {
    id: "q183",
    question: "Quantas pessoas creram na pregação de Pedro no Pentecostes?",
    options: ["120", "500", "Cerca de 3 mil", "Cerca de 5 mil"],
    answer: 2,
    ref: "Atos 2:41",
  },
  {
    id: "q184",
    question: "Quem explicou as Escrituras ao etíope no caminho de Gaza?",
    options: ["Pedro", "Filipe", "Paulo", "Barnabé"],
    answer: 1,
    ref: "Atos 8:30-35",
  },
  {
    id: "q185",
    question: "Quantos dias Saulo ficou sem ver depois da luz no caminho?",
    options: ["1", "3", "7", "40"],
    answer: 1,
    ref: "Atos 9:9",
  },
  {
    id: "q186",
    question: "Quem impôs as mãos sobre Saulo em Damasco para que voltasse a ver?",
    options: ["Ananias", "Barnabé", "Silas", "Áquila"],
    answer: 0,
    ref: "Atos 9:17",
  },
  {
    id: "q187",
    question: "Que discípula de Jope, cheia de boas obras, Pedro ressuscitou?",
    options: ["Lídia", "Tabita", "Febe", "Priscila"],
    answer: 1,
    ref: "Atos 9:40",
  },
  {
    id: "q188",
    question: "Quem cantava hinos na prisão de Filipos quando veio o terremoto?",
    options: ["Pedro e João", "Paulo e Silas", "Paulo e Barnabé", "Silas e Timóteo"],
    answer: 1,
    ref: "Atos 16:25",
  },
  {
    id: "q189",
    question: "Qual era o ofício de Paulo?",
    options: ["Pescador", "Fazedor de tendas", "Carpinteiro", "Cambista"],
    answer: 1,
    ref: "Atos 18:3",
  },
  {
    id: "q190",
    question: "Que vendedora de púrpura se converteu em Filipos?",
    options: ["Lídia", "Dorcas", "Febe", "Cloe"],
    answer: 0,
    ref: "Atos 16:14",
  },
  {
    id: "q191",
    question: "Que jovem caiu da janela durante a longa pregação de Paulo?",
    options: ["Êutico", "Tíquico", "Trófimo", "Timóteo"],
    answer: 0,
    ref: "Atos 20:9-12",
  },
  {
    id: "q192",
    question: "Em que ilha Paulo naufragou a caminho de Roma?",
    options: ["Chipre", "Creta", "Malta", "Patmos"],
    answer: 2,
    ref: "Atos 28:1",
  },
  {
    id: "q193",
    question: "Qual capítulo é conhecido como o capítulo do amor?",
    options: ["Romanos 8", "1 Coríntios 13", "Gálatas 5", "Salmo 91"],
    answer: 1,
    ref: "1 Coríntios 13",
  },
  {
    id: "q194",
    question: "Quantas virtudes compõem o fruto do Espírito em Gálatas?",
    options: ["3", "7", "9", "12"],
    answer: 2,
    ref: "Gálatas 5:22-23",
  },
  {
    id: "q195",
    question: "Na armadura de Deus, a espada do Espírito é...",
    options: ["A fé", "A oração", "A palavra de Deus", "A salvação"],
    answer: 2,
    ref: "Efésios 6:17",
  },
  {
    id: "q196",
    question: "Em que carta está: Tudo posso naquele que me fortalece?",
    options: ["Romanos", "Filipenses", "Tiago", "Hebreus"],
    answer: 1,
    ref: "Filipenses 4:13",
  },
  {
    id: "q197",
    question: "Que capítulo é chamado de galeria dos heróis da fé?",
    options: ["Hebreus 11", "Romanos 12", "Judas 1", "Apocalipse 7"],
    answer: 0,
    ref: "Hebreus 11",
  },
  {
    id: "q198",
    question: "Segundo Tiago, a fé sem obras é...",
    options: ["Fraca", "Incompleta", "Morta", "Pequena"],
    answer: 2,
    ref: "Tiago 2:26",
  },
  {
    id: "q199",
    question: "Em que ilha João recebeu as visões do Apocalipse?",
    options: ["Malta", "Patmos", "Creta", "Rodes"],
    answer: 1,
    ref: "Apocalipse 1:9",
  },
  {
    id: "q200",
    question: "A quantas igrejas o Apocalipse dirige cartas?",
    options: ["3", "7", "10", "12"],
    answer: 1,
    ref: "Apocalipse 1:4",
  },
  {
    id: "q201",
    question: "Quem foi o pai de Matusalém?",
    options: ["Enoque", "Lameque", "Sete", "Jarede"],
    answer: 0,
    ref: "Gênesis 5:21",
  },
  {
    id: "q202",
    question: "Em que monte a arca de Noé repousou?",
    options: ["Sinai", "Ararate", "Moriá", "Hermom"],
    answer: 1,
    ref: "Gênesis 8:4",
  },
  {
    id: "q203",
    question: "Quantas pessoas se salvaram na arca?",
    options: ["6", "8", "12", "40"],
    answer: 1,
    ref: "1 Pedro 3:20",
  },
  {
    id: "q204",
    question: "Quem era o rei e sacerdote que abençoou Abraão?",
    options: ["Melquisedeque", "Abimeleque", "Quedorlaomer", "Faraó"],
    answer: 0,
    ref: "Gênesis 14:18",
  },
  {
    id: "q205",
    question: "Com quem Jacó acabou se casando primeiro, enganado por Labão?",
    options: ["Raquel", "Lia", "Bila", "Zilpa"],
    answer: 1,
    ref: "Gênesis 29:23-25",
  },
  {
    id: "q206",
    question: "Quem era o pai de Raquel e Lia?",
    options: ["Betuel", "Labão", "Naor", "Esaú"],
    answer: 1,
    ref: "Gênesis 29:16",
  },
  {
    id: "q207",
    question: "Quais eram os dois filhos de José?",
    options: ["Manassés e Efraim", "Er e Onã", "Perez e Zerá", "Datã e Abirão"],
    answer: 0,
    ref: "Gênesis 41:51-52",
  },
  {
    id: "q208",
    question: "Quem era o sogro de Moisés?",
    options: ["Jetro", "Labão", "Corá", "Hur"],
    answer: 0,
    ref: "Êxodo 3:1",
  },
  {
    id: "q209",
    question: "Como se chamava a esposa de Moisés?",
    options: ["Miriã", "Zípora", "Ana", "Hulda"],
    answer: 1,
    ref: "Êxodo 2:21",
  },
  {
    id: "q210",
    question: "Quais filhos de Arão morreram por oferecer fogo estranho?",
    options: ["Nadabe e Abiú", "Eleazar e Itamar", "Hofni e Fineias", "Datã e Abirão"],
    answer: 0,
    ref: "Levítico 10:1-2",
  },
  {
    id: "q211",
    question: "Quem liderou a rebelião contra Moisés e foi tragado pela terra?",
    options: ["Corá", "Balaão", "Acã", "Sangar"],
    answer: 0,
    ref: "Números 16:31-33",
  },
  {
    id: "q212",
    question: "De qual tribo de Israel vinham os sacerdotes?",
    options: ["Judá", "Levi", "Benjamim", "Efraim"],
    answer: 1,
    ref: "Números 3:5-10",
  },
  {
    id: "q213",
    question: "Qual juiz canhoto matou o rei Eglom de Moabe?",
    options: ["Sangar", "Eúde", "Otniel", "Ibsã"],
    answer: 1,
    ref: "Juízes 3:15-21",
  },
  {
    id: "q214",
    question: "Quem feriu 600 filisteus com uma aguilhada de bois?",
    options: ["Sansão", "Sangar", "Eúde", "Tola"],
    answer: 1,
    ref: "Juízes 3:31",
  },
  {
    id: "q215",
    question: "Qual juiz fez um voto precipitado que envolveu sua única filha?",
    options: ["Gideão", "Jefté", "Abdom", "Elom"],
    answer: 1,
    ref: "Juízes 11:30-35",
  },
  {
    id: "q216",
    question: "Qual mulher impediu que Davi se vingasse de Nabal?",
    options: ["Mical", "Abigail", "Bate-Seba", "Ainoã"],
    answer: 1,
    ref: "1 Samuel 25:23-33",
  },
  {
    id: "q217",
    question: "Qual esposa desprezou Davi por dançar diante da arca?",
    options: ["Abigail", "Mical", "Bate-Seba", "Ainoã"],
    answer: 1,
    ref: "2 Samuel 6:16",
  },
  {
    id: "q218",
    question: "Quem morreu ao estender a mão para segurar a arca?",
    options: ["Uzá", "Aío", "Obede-Edom", "Geazi"],
    answer: 0,
    ref: "2 Samuel 6:6-7",
  },
  {
    id: "q219",
    question: "Quem era o comandante do exército de Davi?",
    options: ["Abner", "Joabe", "Amasa", "Urias"],
    answer: 1,
    ref: "2 Samuel 8:16",
  },
  {
    id: "q220",
    question: "Que filho de Saul reinou sobre Israel após a morte do pai?",
    options: ["Jônatas", "Isbosete", "Mefibosete", "Abinadabe"],
    answer: 1,
    ref: "2 Samuel 2:8-10",
  },
  {
    id: "q221",
    question: "Qual rei de Israel fundou a cidade de Samaria?",
    options: ["Acabe", "Onri", "Jeú", "Jeroboão"],
    answer: 1,
    ref: "1 Reis 16:24",
  },
  {
    id: "q222",
    question: "De quem era a vinha que o rei Acabe cobiçou?",
    options: ["Nabote", "Obadias", "Geazi", "Eliabe"],
    answer: 0,
    ref: "1 Reis 21:1-3",
  },
  {
    id: "q223",
    question: "Qual servo de Eliseu ficou leproso por causa da ganância?",
    options: ["Geazi", "Obadias", "Baruque", "Eliaquim"],
    answer: 0,
    ref: "2 Reis 5:25-27",
  },
  {
    id: "q224",
    question: "Que rainha matou a descendência real e usurpou o trono de Judá?",
    options: ["Jezabel", "Atalia", "Vasti", "Herodias"],
    answer: 1,
    ref: "2 Reis 11:1-3",
  },
  {
    id: "q225",
    question: "Qual menino-rei foi escondido no templo por seis anos?",
    options: ["Josias", "Joás", "Manassés", "Uzias"],
    answer: 1,
    ref: "2 Reis 11:2-3",
  },
  {
    id: "q226",
    question: "Que sumo sacerdote achou o livro da Lei no templo?",
    options: ["Hilquias", "Esdras", "Eliasibe", "Zadoque"],
    answer: 0,
    ref: "2 Reis 22:8",
  },
  {
    id: "q227",
    question: "Qual profetisa confirmou ao rei Josias as palavras do livro achado?",
    options: ["Débora", "Hulda", "Ana", "Noadia"],
    answer: 1,
    ref: "2 Reis 22:14-16",
  },
  {
    id: "q228",
    question: "Qual rei da Pérsia autorizou a volta dos judeus do cativeiro?",
    options: ["Dario", "Ciro", "Artaxerxes", "Assuero"],
    answer: 1,
    ref: "Esdras 1:1-3",
  },
  {
    id: "q229",
    question: "Quem liderou a reconstrução do templo na volta do exílio?",
    options: ["Neemias", "Zorobabel", "Esdras", "Zadoque"],
    answer: 1,
    ref: "Esdras 3:8",
  },
  {
    id: "q230",
    question: "Quais profetas animaram o povo a retomar a obra do templo?",
    options: ["Ageu e Zacarias", "Naum e Habacuque", "Joel e Amós", "Miqueias e Sofonias"],
    answer: 0,
    ref: "Esdras 5:1-2",
  },
  {
    id: "q231",
    question: "Qual era o ofício de Neemias na corte da Pérsia?",
    options: ["Escriba", "Copeiro do rei", "Tesoureiro", "Governador"],
    answer: 1,
    ref: "Neemias 1:11",
  },
  {
    id: "q232",
    question: "Quantos anos de cativeiro na Babilônia Jeremias profetizou?",
    options: ["40", "70", "100", "400"],
    answer: 1,
    ref: "Jeremias 25:11",
  },
  {
    id: "q233",
    question: "Qual era o outro nome de Ester?",
    options: ["Hadassa", "Zeres", "Abigail", "Quetura"],
    answer: 0,
    ref: "Ester 2:7",
  },
  {
    id: "q234",
    question: "Quem disse: Ainda que ele me mate, nele esperarei?",
    options: ["Davi", "Jó", "Jeremias", "Paulo"],
    answer: 1,
    ref: "Jó 13:15",
  },
  {
    id: "q235",
    question: "Complete: Lâmpada para os meus pés é a tua palavra e...",
    options: ["luz para o meu caminho", "guia para os meus passos", "farol para a minha vida", "norte para os meus dias"],
    answer: 0,
    ref: "Salmo 119:105",
  },
  {
    id: "q236",
    question: "Quantos são os Cânticos de Degraus (ou de Subida) nos Salmos?",
    options: ["7", "10", "15", "24"],
    answer: 2,
    ref: "Salmos 120–134",
  },
  {
    id: "q237",
    question: "Que salmo Jesus citou na cruz: Deus meu, Deus meu...?",
    options: ["Salmo 22", "Salmo 23", "Salmo 51", "Salmo 91"],
    answer: 0,
    ref: "Salmo 22:1; Mateus 27:46",
  },
  {
    id: "q238",
    question: "Em que ano Isaías viu o Senhor alto e sublime?",
    options: ["No ano da morte do rei Uzias", "No ano do terremoto", "No jubileu", "No ano da queda de Samaria"],
    answer: 0,
    ref: "Isaías 6:1",
  },
  {
    id: "q239",
    question: "Em que foi lançado Jeremias por profetizar a verdade?",
    options: ["Numa fornalha", "Numa cisterna de lama", "Numa prisão romana", "Num poço seco no deserto"],
    answer: 1,
    ref: "Jeremias 38:6",
  },
  {
    id: "q240",
    question: "Quem tirou Jeremias da cisterna?",
    options: ["Baruque", "Ebede-Meleque", "Gedalias", "Seraías"],
    answer: 1,
    ref: "Jeremias 38:7-13",
  },
  {
    id: "q241",
    question: "Quem teve a visão do vale de ossos secos?",
    options: ["Daniel", "Ezequiel", "Zacarias", "Joel"],
    answer: 1,
    ref: "Ezequiel 37:1-10",
  },
  {
    id: "q242",
    question: "Qual rei comeu capim como boi até reconhecer o Altíssimo?",
    options: ["Belsazar", "Nabucodonosor", "Dario", "Ciro"],
    answer: 1,
    ref: "Daniel 4:33-34",
  },
  {
    id: "q243",
    question: "Qual profeta era boiadeiro e cultivador de sicômoros?",
    options: ["Oseias", "Amós", "Obadias", "Naum"],
    answer: 1,
    ref: "Amós 7:14",
  },
  {
    id: "q244",
    question: "Qual profeta casou-se com Gômer por ordem do Senhor?",
    options: ["Oseias", "Joel", "Miqueias", "Malaquias"],
    answer: 0,
    ref: "Oseias 1:2-3",
  },
  {
    id: "q245",
    question: "Contra qual nação é a profecia de Obadias?",
    options: ["Moabe", "Edom", "Assíria", "Babilônia"],
    answer: 1,
    ref: "Obadias 1",
  },
  {
    id: "q246",
    question: "De qual profeta é a frase: o justo viverá pela sua fé?",
    options: ["Sofonias", "Habacuque", "Ageu", "Naum"],
    answer: 1,
    ref: "Habacuque 2:4",
  },
  {
    id: "q247",
    question: "Qual evangelho narra a visita dos pastores ao menino Jesus?",
    options: ["Mateus", "Marcos", "Lucas", "João"],
    answer: 2,
    ref: "Lucas 2:8-16",
  },
  {
    id: "q248",
    question: "Qual apóstolo era chamado de Zelote?",
    options: ["Simão", "Judas Tadeu", "Tiago de Alfeu", "Bartolomeu"],
    answer: 0,
    ref: "Lucas 6:15",
  },
  {
    id: "q249",
    question: "Qual discípulo era natural de Caná da Galileia?",
    options: ["Natanael", "Filipe", "André", "Tomé"],
    answer: 0,
    ref: "João 21:2",
  },
  {
    id: "q250",
    question: "O que significa Eloí, Eloí, lamá sabactâni?",
    options: ["Deus meu, Deus meu, por que me desamparaste?", "Nas tuas mãos entrego o meu espírito", "Está consumado", "Pai, perdoa-lhes"],
    answer: 0,
    ref: "Marcos 15:34",
  },
  {
    id: "q251",
    question: "Qual discípulo de Emaús é citado pelo nome?",
    options: ["Cleopas", "Nicodemos", "José", "Simeão"],
    answer: 0,
    ref: "Lucas 24:18",
  },
  {
    id: "q252",
    question: "Qual o nome aramaico do campo comprado com as moedas de Judas?",
    options: ["Aceldama", "Gabatá", "Golgota", "Betesda"],
    answer: 0,
    ref: "Atos 1:19",
  },
  {
    id: "q253",
    question: "Que mestre da lei aconselhou o sinédrio a não matar os apóstolos?",
    options: ["Gamaliel", "Caifás", "Anás", "Nicodemos"],
    answer: 0,
    ref: "Atos 5:34-39",
  },
  {
    id: "q254",
    question: "Aos pés de quem Paulo disse ter sido instruído?",
    options: ["Gamaliel", "Caifás", "Apolo", "Barnabé"],
    answer: 0,
    ref: "Atos 22:3",
  },
  {
    id: "q255",
    question: "Em que cidade Paulo foi apedrejado e deixado como morto?",
    options: ["Icônio", "Listra", "Derbe", "Antioquia"],
    answer: 1,
    ref: "Atos 14:19",
  },
  {
    id: "q256",
    question: "Que mágico se opôs a Paulo diante do procônsul em Chipre?",
    options: ["Simão", "Elimas", "Cerinto", "Alexandre"],
    answer: 1,
    ref: "Atos 13:8",
  },
  {
    id: "q257",
    question: "Qual ourives levantou o tumulto contra Paulo em Éfeso?",
    options: ["Demétrio", "Alexandre", "Áquila", "Erasto"],
    answer: 0,
    ref: "Atos 19:24-29",
  },
  {
    id: "q258",
    question: "Em que tribunal de Atenas Paulo pregou sobre o Deus desconhecido?",
    options: ["No Pórtico", "No Areópago", "Na Ágora", "No Liceu"],
    answer: 1,
    ref: "Atos 17:19-23",
  },
  {
    id: "q259",
    question: "Qual anjo é chamado de arcanjo na Bíblia?",
    options: ["Gabriel", "Miguel", "Rafael", "Uriel"],
    answer: 1,
    ref: "Judas 9",
  },
  {
    id: "q260",
    question: "Quantos anciãos estão ao redor do trono no Apocalipse?",
    options: ["12", "24", "70", "144"],
    answer: 1,
    ref: "Apocalipse 4:4",
  },
];
